# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-03 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0002_auto_20160403_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='level',
        ),
        migrations.AlterField(
            model_name='level',
            name='level',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.AddField(
            model_name='upload',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Archive.Level'),
        ),
    ]
