# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0007_auto_20160404_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
