# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Archive', '0009_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='upload',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upload_comment', to='Archive.Upload'),
            preserve_default=False,
        ),
    ]
